-- Scope payment idempotency keys per customer instead of globally.
--
-- An idempotency key is generated by the client, so two different customers can
-- legitimately send the same string. The previous GLOBAL unique index turned
-- that into a 409 for whichever customer asked second, and disclosed that
-- somebody else's key existed. `payments.user_id` is added and backfilled from
-- the owning order because a unique index cannot span the order relation; every
-- payment has an order, so the column is safe to make NOT NULL, which the
-- compound unique also needs (PostgreSQL treats NULLs as distinct, so a nullable
-- `user_id` would have enforced nothing).

ALTER TABLE "payments" ADD COLUMN "user_id" UUID;

UPDATE "payments" AS p
SET "user_id" = o."user_id"
FROM "orders" AS o
WHERE o."id" = p."order_id";

ALTER TABLE "payments" ALTER COLUMN "user_id" SET NOT NULL;

-- Replace the global uniqueness with per-customer uniqueness.
DROP INDEX IF EXISTS "payments_idempotency_key_key";

CREATE UNIQUE INDEX "payments_user_id_idempotency_key_key"
  ON "payments"("user_id", "idempotency_key");

CREATE INDEX "payments_user_id_idx" ON "payments"("user_id");

ALTER TABLE "payments"
  ADD CONSTRAINT "payments_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "users"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
