import type { CurrencyCode, OrderStatus, Paise } from '@sakya/types';

/** Response shapes for the cart and checkout endpoints.

Cart responses intentionally exclude anything the client did not supply or that
the server recomputes: the client never sends prices, and the server never
trusts them. Line totals, subtotal, discount, tax, shipping and total are always
recomputed on every read.

Order responses snapshot the product/variant titles at placement time so a later
catalog edit cannot rewrite what the customer actually bought.
*/

/** One line in the cart. Prices are snapshots taken server-side when added. */
export interface CartItemResponse {
  id: string;
  variantId: string;
  /** Product title snapshot taken when the item was added. */
  productTitle: string;
  /** Variant title snapshot taken when the item was added. */
  variantTitle: string;
  /** The product's first display image, resolved server-side. Null when none. */
  productImageUrl: string | null;
  /** The product's slug, so the cart can link back to the detail page. */
  productSlug: string;
  sku: string | null;
  quantity: number;
  /** Server-computed line total, in paise. */
  lineTotalInPaise: Paise;
  /** Unit price in paise at the time the item was added. */
  unitPriceInPaise: Paise;
  /** Whether the referenced variant is currently available for sale. */
  isAvailable: boolean;
}

/** The current cart with server-computed totals. */
export interface CartResponse {
  id: string;
  /** Opaque client identifier used before the user signs in. Null once owned. */
  anonymousId: string | null;
  status: string;
  currency: CurrencyCode;
  expiresAt: string | null;
  items: CartItemResponse[];
  /** Sum of every line total, in paise. Server-computed. */
  subtotalInPaise: Paise;
  /** Discount applied, in paise. Server-computed. */
  discountInPaise: Paise;
  /** Tax computed server-side from the subtotal. Placeholder; not a tax engine. */
  taxInPaise: Paise;
  /** Shipping computed server-side. Placeholder; not a shipping engine. */
  shippingInPaise: Paise;
  /** subtotal - discount + tax + shipping, in paise. Server-computed. */
  totalInPaise: Paise;
  /** Coupon currently applied, if any. */
  coupon: AppliedCouponResponse | null;
}

/** A coupon applied to the cart. */
export interface AppliedCouponResponse {
  id: string;
  code: string;
  type: string;
  valueInPaise: Paise;
  /** How the value should be interpreted. */
  discountDescription: string;
}

/** Inputs for adding or updating a cart item. */

export interface AddCartItemRequest {
  /** Variant to add. The server reads the price from the database, never from here. */
  variantId: string;
  /** Store the variant belongs to / the cart is scoped to. */
  storeId: string;
  /** Quantity to stock in the cart. */
  quantity: number;
}

export interface UpdateCartItemRequest {
  /** New quantity. The server recomputes the line total from the stored unit price. */
  quantity: number;
}

/** Request to apply a coupon to the cart. */
export interface ApplyCouponRequest {
  code: string;
}

/** Request to place an order from the current cart. */

export interface CheckoutRequest {
  /** Idempotency key generated by the client. Reuse is rejected. */
  idempotencyKey: string;
  /** Snapshots of the shipping and billing addresses the order is fulfilled against. */
  shippingAddress: Record<string, unknown>;
  billingAddress?: Record<string, unknown> | null;
  notes?: string | null;
}

/** One line in a placed order. Immutable: prices and titles are snapshotted. */
export interface OrderItemResponse {
  id: string;
  /** Product title at the time the order was placed. */
  productTitle: string;
  /** Variant title at the time the order was placed. */
  variantTitle: string;
  sku: string | null;
  quantity: number;
  unitPriceInPaise: Paise;
  discountInPaise: Paise;
  taxInPaise: Paise;
  totalInPaise: Paise;
}

/** One payment attempt against an order. */
export interface PaymentResponse {
  id: string;
  provider: string;
  providerPaymentId: string | null;
  method: string;
  status: string;
  currency: CurrencyCode;
  amountInPaise: Paise;
  refundedInPaise: Paise;
  failureReason: string | null;
  capturedAt: string | null;
  refundedAt: string | null;
}

/** A status change record for an order. */
export interface OrderStatusHistoryResponse {
  id: string;
  fromStatus: OrderStatus | null;
  toStatus: OrderStatus;
  reason: string | null;
  changedByUserId: string | null;
  createdAt: string;
}

/** A placed order. */
export interface OrderResponse {
  id: string;
  orderNumber: string;
  status: string;
  paymentStatus: string;
  currency: CurrencyCode;
  subtotalInPaise: Paise;
  discountInPaise: Paise;
  taxInPaise: Paise;
  shippingInPaise: Paise;
  totalInPaise: Paise;
  coupon: AppliedCouponResponse | null;
  items: OrderItemResponse[];
  payments: PaymentResponse[];
  statusHistory: OrderStatusHistoryResponse[];
  shippingAddress: Record<string, unknown>;
  billingAddress: Record<string, unknown> | null;
  notes: string | null;
  placedAt: string | null;
  cancelledAt: string | null;
  deliveredAt: string | null;
  cancelReason: string | null;
  createdAt: string;
  updatedAt: string;
}

/** List envelope for the caller's orders. */
export interface OrdersResponse {
  items: OrderResponse[];
  meta: {
    page: number;
    perPage: number;
    total: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
  };
}
