import type { INestApplication } from '@nestjs/common';
import { JwtService, type JwtSignOptions } from '@nestjs/jwt';
import { Test } from '@nestjs/testing';
import { PrismaPg } from '@prisma/adapter-pg';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import { PrismaClient } from '../src/generated/prisma/client';
import { AppModule } from '../src/app.module';
import { configureApp } from '../src/app.setup';
import configuration from '../src/config/configuration';

/**
 * Payment idempotency keys are scoped per customer, not globally.
 *
 * A key is generated by the client, so two customers can legitimately send the
 * same string. When the column carried a global unique index, the second
 * customer's checkout failed with a 409 that had nothing to do with them (and
 * disclosed that someone else's key existed). These tests pin the per-customer
 * behaviour at the database constraint and at the HTTP boundary.
 *
 * Runs only when `RUN_DB_E2E=1` and a disposable `DATABASE_URL` is configured.
 */

const CUSTOMER_A_EMAIL = 'idempotency-a@sakyafarms.example';
const CUSTOMER_B_EMAIL = 'idempotency-b@sakyafarms.example';
const PASSWORD = 'TestPassword123!';

const STORE_ID = 'c1111111-1111-4111-8111-111111111111';
const PRODUCT_ID = 'c2222222-2222-4222-8222-222222222222';
const VARIANT_ID = 'c3333333-3333-4333-8333-333333333333';

const SHARED_KEY = 'shared-idempotency-key';
const RETRY_KEY = 'retry-idempotency-key';

interface Actor {
  id: string;
  token: string;
}

interface TestContext {
  app: INestApplication;
  prisma: PrismaClient;
  baseUrl: string;
  a: Actor;
  b: Actor;
}

const runDatabaseE2e = process.env.RUN_DB_E2E === '1';

async function passwordHash(): Promise<string> {
  const { hash } = await import('@node-rs/argon2');
  return hash(PASSWORD, { algorithm: 2, memoryCost: 19456, timeCost: 2, parallelism: 1 });
}

async function upsertCustomer(prisma: PrismaClient, email: string, hash: string) {
  const user = await prisma.user.upsert({
    where: { email },
    update: { passwordHash: hash, status: 'ACTIVE' },
    create: {
      email,
      passwordHash: hash,
      firstName: 'Idempotency',
      lastName: 'Test',
      status: 'ACTIVE',
      emailVerifiedAt: new Date(),
    },
  });

  const role = await prisma.role.findUniqueOrThrow({ where: { code: 'CUSTOMER' } });
  await prisma.userRole.upsert({
    where: { userId_roleId: { userId: user.id, roleId: role.id } },
    update: {},
    create: { userId: user.id, roleId: role.id },
  });

  return user;
}

async function seedTestData(prisma: PrismaClient) {
  const store = await prisma.store.upsert({
    where: { id: STORE_ID },
    update: { isActive: true },
    create: {
      id: STORE_ID,
      code: 'IDEMPOTENCY-TEST',
      name: 'Idempotency Test Store',
      isActive: true,
    },
  });

  const product = await prisma.product.upsert({
    where: { id: PRODUCT_ID },
    update: {},
    create: {
      id: PRODUCT_ID,
      sourcePlatform: 'MANUAL',
      sourceProductId: 'idempotency-test-product',
      sourceHandle: 'idempotency-test-product',
      title: 'Idempotency Test Honey',
      slug: 'idempotency-test-honey',
      status: 'ACTIVE',
      isAvailable: true,
      publishedAt: new Date(),
    },
  });

  const variant = await prisma.productVariant.upsert({
    where: { id: VARIANT_ID },
    update: {},
    create: {
      id: VARIANT_ID,
      productId: product.id,
      title: '250 g',
      sku: 'IDEMPOTENCY-250G',
      priceInPaise: 1500,
      currency: 'INR',
      isAvailable: true,
    },
  });

  return { store, variant };
}

async function resetInventory(prisma: PrismaClient) {
  await prisma.inventoryMovement.deleteMany({
    where: { variantId: VARIANT_ID, storeId: STORE_ID },
  });
  await prisma.inventory.upsert({
    where: { variantId_storeId: { variantId: VARIANT_ID, storeId: STORE_ID } },
    update: { quantityOnHand: 100, quantityReserved: 0 },
    create: {
      variantId: VARIANT_ID,
      storeId: STORE_ID,
      quantityOnHand: 100,
      quantityReserved: 0,
      reorderLevel: 2,
    },
  });
}

async function clearCustomerData(prisma: PrismaClient, userId: string) {
  await prisma.$transaction(async (tx) => {
    await tx.cartItem.deleteMany({ where: { cart: { userId } } });
    await tx.cart.deleteMany({ where: { userId } });
    await tx.payment.deleteMany({ where: { order: { userId } } });
    await tx.order.deleteMany({ where: { userId } });
  });
}

function signIn(user: { id: string }): string {
  const config = configuration();
  const jwt = new JwtService({
    secret: config.auth.accessSecret,
    signOptions: {
      algorithm: 'HS256',
      expiresIn: config.auth.accessTtl as unknown as JwtSignOptions['expiresIn'],
      issuer: config.auth.issuer,
      audience: config.auth.audience,
    },
  });

  return jwt.sign({ sub: user.id, typ: 'access' });
}

describe.skipIf(!runDatabaseE2e)('Payment idempotency scoping (seeded DB)', () => {
  let ctx: TestContext;

  beforeAll(async () => {
    const prisma = new PrismaClient({
      adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL }),
    });
    await prisma.$connect();

    await seedTestData(prisma);
    await resetInventory(prisma);

    const hash = await passwordHash();
    const userA = await upsertCustomer(prisma, CUSTOMER_A_EMAIL, hash);
    const userB = await upsertCustomer(prisma, CUSTOMER_B_EMAIL, hash);

    await clearCustomerData(prisma, userA.id);
    await clearCustomerData(prisma, userB.id);

    const module = await Test.createTestingModule({ imports: [AppModule] }).compile();
    const app = module.createNestApplication();
    configureApp(app);
    await app.init();

    const server = (await app.listen(0)) as { address(): { port: number } | null };
    const port = server.address()?.port ?? 0;

    ctx = {
      app,
      prisma,
      baseUrl: `http://127.0.0.1:${port}/api/v1`,
      a: { id: userA.id, token: signIn(userA) },
      b: { id: userB.id, token: signIn(userB) },
    };
  });

  afterAll(async () => {
    // Remove this suite's fixtures so the shared catalog never shows test rows.
    if (ctx) {
      await ctx.prisma.cartItem.deleteMany({ where: { variant: { productId: PRODUCT_ID } } });
      await ctx.prisma.productCategory.deleteMany({ where: { productId: PRODUCT_ID } });
      await ctx.prisma.productVariant.deleteMany({ where: { productId: PRODUCT_ID } });
      await ctx.prisma.product.deleteMany({ where: { id: PRODUCT_ID } });
    }
    await ctx?.app.close();
    await ctx?.prisma.$disconnect();
  });

  afterEach(async () => {
    if (ctx === undefined) return;
    await clearCustomerData(ctx.prisma, ctx.a.id);
    await clearCustomerData(ctx.prisma, ctx.b.id);
    await resetInventory(ctx.prisma);
  });

  async function checkout(
    actor: Actor,
    idempotencyKey: string,
  ): Promise<{ status: number; body: { id: string; orderNumber: string } }> {
    const added = await fetch(ctx.baseUrl + '/cart/items', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${actor.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ variantId: VARIANT_ID, storeId: STORE_ID, quantity: 1 }),
    });
    expect(added.status).toBe(201);

    const res = await fetch(ctx.baseUrl + '/orders', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${actor.token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        idempotencyKey,
        shippingAddress: { line1: 'Home', city: 'Bengaluru' },
        billingAddress: null,
        notes: null,
      }),
    });

    return { status: res.status, body: (await res.json()) as { id: string; orderNumber: string } };
  }

  it('lets two customers use the same idempotency key', async () => {
    const first = await checkout(ctx.a, SHARED_KEY);
    const second = await checkout(ctx.b, SHARED_KEY);

    expect(first.status).toBe(201);
    expect(second.status).toBe(201);

    // Independently created orders — the key is theirs, not a shared namespace.
    expect(first.body.id).not.toBe(second.body.id);
    expect(first.body.orderNumber).not.toBe(second.body.orderNumber);

    // One payment per customer, each owned by its own customer.
    const payments = await ctx.prisma.payment.findMany({
      where: { idempotencyKey: SHARED_KEY },
      select: { userId: true, orderId: true },
    });
    expect(payments).toHaveLength(2);
    expect(new Set(payments.map((payment) => payment.userId))).toEqual(
      new Set([ctx.a.id, ctx.b.id]),
    );
    expect(payments.some((payment) => payment.orderId === first.body.id)).toBe(true);
    expect(payments.some((payment) => payment.orderId === second.body.id)).toBe(true);
  });

  it('returns the caller own order on a retry, and only creates one order', async () => {
    const first = await checkout(ctx.a, RETRY_KEY);
    expect(first.status).toBe(201);

    const retry = await checkout(ctx.a, RETRY_KEY);

    // A retry is answered with the original order, not a new one and not the
    // other customer's.
    expect(retry.status).toBe(201);
    expect(retry.body.id).toBe(first.body.id);
    expect(retry.body.orderNumber).toBe(first.body.orderNumber);

    expect(await ctx.prisma.order.count({ where: { userId: ctx.a.id } })).toBe(1);
    expect(await ctx.prisma.payment.count({ where: { userId: ctx.a.id } })).toBe(1);
  });

  it('still refuses to reuse one customer key for a second of their orders', async () => {
    const first = await checkout(ctx.a, SHARED_KEY);
    expect(first.status).toBe(201);

    // A second order for the same customer (checkout leaves the cart intact).
    const second = await checkout(ctx.a, 'another-key');
    expect(second.status).toBe(201);
    expect(second.body.id).not.toBe(first.body.id);

    // The compound unique is (user, key): reusing the key inside one account is
    // still rejected, which is the double-charge guard.
    await expect(
      ctx.prisma.payment.create({
        data: {
          orderId: second.body.id,
          userId: ctx.a.id,
          provider: 'MANUAL',
          method: 'CASH_ON_DELIVERY',
          status: 'PENDING',
          currency: 'INR',
          amountInPaise: 1500,
          idempotencyKey: SHARED_KEY,
        },
      }),
    ).rejects.toThrow();

    // …while the other customer's identically-keyed payment is untouched.
    expect(await ctx.prisma.payment.count({ where: { idempotencyKey: SHARED_KEY } })).toBe(1);
  });
});
